import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ReactQueryProvider from '@/lib/react-query/ReactQueryProvider';
import MSWComponent from '@/components/MSWComponent';
import styles from './layout.module.scss';
import '@/styles/global.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryProvider>
          <MSWComponent />
          <Header />
          <div className={styles.container}>{children}</div>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
